apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "common.trinnex.labels" . | nindent 4 }}
    {{- include "common.leadcast.labels" . | nindent 4 }}
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http-dotnet
      protocol: TCP
      name: http
    - port: {{ .Values.service.https.port }}
      targetPort: https-dotnet
      protocol: TCP
      name: https
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
